# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [56]:
from IPython.display import display

In [7]:
import pandas as pd
import numpy as np
df1=pd.DataFrame(np.random.randint(1,11,size=(6,4)),columns=['A','B','C','D'])
print(df1)

df1.set_index('A',inplace=True)
df1

    A  B  C  D
0   8  8  1  4
1   1  3  2  6
2  10  7  5  8
3   4  1  2  1
4   8  1  6  9
5   4  7  3  2

    B  C  D
A
8   8  1  4
1   3  2  6
10  7  5  8
4   1  2  1
8   1  6  9
4   7  3  2

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [11]:
df12=pd.DataFrame(np.random.randint(1,11,size=(3,3)),columns=['A','B','C'],index=['X','Y','Z'])
print(df12)
df12.loc['Y']['B']

   A  B  C
X  9  2  6
Y  9  2  7
Z  4  5  3

np.int32(2)

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [13]:
df2=pd.DataFrame(np.random.randint(1,11,size=(5,3)))
print(df2)
df2[3]=df2[0]*df2[1]
df2

   0  1  2
0  8  5  7
1  7  4  4
2  2  3  9
3  7  5  7
4  7  3  9

   0  1  2   3
0  8  5  7  40
1  7  4  4  28
2  2  3  9   6
3  7  5  7  35
4  7  3  9  21

2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [23]:
df22=pd.DataFrame(np.random.randint(1,11,size=(4,3)))
print(df22)
row_sum=df22.sum(axis=1)
print('row sum:\n',row_sum)
col_sum=df22.sum(axis=0)
print('col sum:\n',col_sum)

   0   1  2
0  2   6  1
1  8  10  3
2  2   2  1
3  1   3  3
row sum:
 0     9
1    21
2     5
3     7
dtype: int64
col sum:
 0    13
1    21
2     8
dtype: int64

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [25]:
df3=pd.DataFrame(np.random.randint(1,11,size=(5,3)))
print(df3)


df3.iloc[0,2]=np.nan
df3.loc[3,1]=np.nan

print(df3)

df3.fillna(df3.mean(),inplace=True)
print('df3 updated:\n',df3)

   0   1  2
0  7   4  9
1  1   9  2
2  9   8  3
3  1   7  5
4  5  10  4
   0     1    2
0  7   4.0  NaN
1  1   9.0  2.0
2  9   8.0  3.0
3  1   NaN  5.0
4  5  10.0  4.0
df3 updated:
    0      1    2
0  7   4.00  3.5
1  1   9.00  2.0
2  9   8.00  3.0
3  1   7.75  5.0
4  5  10.00  4.0

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [27]:
df32=pd.DataFrame(np.random.randint(1,11,size=(6,4)))
df32.iloc[0,2]=np.nan
df32.loc[3,1]=np.nan
print('original:\n',df32)
df32.dropna(inplace=True)
print('na dropped df32:\n',df32)

original:
     0    1    2   3
0   9  1.0  NaN   7
1   3  3.0  6.0   3
2   3  8.0  5.0   1
3   9  NaN  1.0   1
4  10  6.0  1.0  10
5   1  9.0  8.0   5
na dropped df32:
     0    1    2   3
1   3  3.0  6.0   3
2   3  8.0  5.0   1
4  10  6.0  1.0  10
5   1  9.0  8.0   5

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [31]:
df4=pd.DataFrame({'Category':np.random.choice(['A','B','C'],size=10),'Values':np.random.randint(1,11,size=10)})
print('original DataFrame:\n',df4)

sum=df4.groupby('Category').sum()
print(sum)
mean=df4.groupby('Category').mean()
print(mean)

original DataFrame:
   Category  Values
0        A       5
1        B       2
2        B       2
3        B       1
4        A       2
5        C       1
6        C       4
7        B       1
8        C       2
9        B       7
          Values
Category
A              7
B             13
C              7
            Values
Category
A         3.500000
B         2.600000
C         2.333333

2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [36]:
df42=pd.DataFrame({'Product':np.random.choice(['prod1','prod2','prod3'],size=10),
                   'Category':np.random.choice(['cat1','cat2','cat3'],size=10),
                   'Sales':np.random.randint(1,1000,size=10)})

print(df42)

print(df42.groupby('Category')['Sales'].sum())

  Product Category  Sales
0   prod3     cat1    141
1   prod2     cat2    520
2   prod2     cat1    450
3   prod1     cat2    459
4   prod3     cat2    821
5   prod3     cat3    555
6   prod2     cat1    479
7   prod3     cat3     81
8   prod1     cat2    879
9   prod1     cat3    624
Category
cat1    1070
cat2    2679
cat3    1260
Name: Sales, dtype: int32

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [42]:
df5=pd.DataFrame({'key':[1,2,3,4,5],'Value1':[6,7,8,9,10],'Value2':[11,12,13,14,15]})
print(df5)
df_5=pd.DataFrame({'key':[1,2,3,4,5],'Value3':[16,17,18,19,20]})
print(df_5)

merged=pd.merge(df5,df_5,on='key')
print(merged)

   key  Value1  Value2
0    1       6      11
1    2       7      12
2    3       8      13
3    4       9      14
4    5      10      15
   key  Value3
0    1      16
1    2      17
2    3      18
3    4      19
4    5      20
   key  Value1  Value2  Value3
0    1       6      11      16
1    2       7      12      17
2    3       8      13      18
3    4       9      14      19
4    5      10      15      20

2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [47]:
df5=pd.DataFrame(np.random.randint(1,101,size=(5,3)),columns=[1,2,3])
print(df5)
df_5=pd.DataFrame(np.random.randint(1,101,size=(5,2)),columns=[3,4])
print(df_5)


concat_rows=pd.concat([df5,df_5],axis=0)
print('concatenated on rows:\n',concat_rows)

concat_col=pd.concat([df5,df_5],axis=1)
print('concatenated on cols:\n',concat_col)

    1   2   3
0  45   1   8
1  57  57  71
2  92  56  44
3   8  80  16
4  53  52  63
    3   4
0  68   1
1  20   8
2  68  14
3  43  78
4  58  69
concatenated on rows:
       1     2   3     4
0  45.0   1.0   8   NaN
1  57.0  57.0  71   NaN
2  92.0  56.0  44   NaN
3   8.0  80.0  16   NaN
4  53.0  52.0  63   NaN
0   NaN   NaN  68   1.0
1   NaN   NaN  20   8.0
2   NaN   NaN  68  14.0
3   NaN   NaN  43  78.0
4   NaN   NaN  58  69.0
concatenated on cols:
     1   2   3   3   4
0  45   1   8  68   1
1  57  57  71  20   8
2  92  56  44  68  14
3   8  80  16  43  78
4  53  52  63  58  69

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [58]:
date_rng=pd.date_range(start='2025-01-01',end='2025-12-31',freq='D')
df6=pd.DataFrame(date_rng,columns=['date'])
df6['data']=np.random.randint(1,101,size=(len(date_rng)))
display(df6.head(10))

df6.set_index('date',inplace=True)
display(df6.head(5))

Monthly_Mean=df6.resample('M').mean()
Monthly_Mean

        date  data
0 2025-01-01    74
1 2025-01-02    59
2 2025-01-03    83
3 2025-01-04    59
4 2025-01-05    56
5 2025-01-06    38
6 2025-01-07    97
7 2025-01-08    98
8 2025-01-09    64
9 2025-01-10   100

            data
date
2025-01-01    74
2025-01-02    59
2025-01-03    83
2025-01-04    59
2025-01-05    56

C:\Users\ABRAR\AppData\Local\Temp\ipykernel_12292\3148555520.py:9: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  Monthly_Mean=df6.resample('M').mean()

                 data
date
2025-01-31  54.419355
2025-02-28  52.821429
2025-03-31  46.741935
2025-04-30  54.666667
2025-05-31  48.935484
2025-06-30  52.966667
2025-07-31  48.387097
2025-08-31  55.806452
2025-09-30  45.000000
2025-10-31  48.709677
2025-11-30  61.266667
2025-12-31  43.903226

2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [63]:
date_rng=pd.date_range(start='2021-01-01',end='2021-12-31',freq='D')
df62=pd.DataFrame(date_rng,columns=['Date'])
df62['Data']=np.random.randint(1,101,size=len(date_rng))
df62.set_index('Date',inplace=True)
display(df62)

mean=df62.rolling(window=7).mean()
mean.head(10)

            Data
Date
2021-01-01    45
2021-01-02     5
2021-01-03    79
2021-01-04    92
2021-01-05    86
...          ...
2021-12-27    85
2021-12-28    22
2021-12-29     3
2021-12-30     9
2021-12-31    27

[365 rows x 1 columns]

                 Data
Date
2021-01-01        NaN
2021-01-02        NaN
2021-01-03        NaN
2021-01-04        NaN
2021-01-05        NaN
2021-01-06        NaN
2021-01-07  57.714286
2021-01-08  60.428571
2021-01-09  62.142857
2021-01-10  58.857143

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [70]:
array=[[1,2,3,4,5],['A','B','C','D','E']]
index=pd.MultiIndex.from_arrays(array,names=['Category','Sub-cat'])
df7=pd.DataFrame(np.random.randint(1,101,size=(5,3)),index=index,columns=['col1','col2','col3'])

display(df7)

display(df7.loc[(2,'B'),:])

                  col1  col2  col3
Category Sub-cat
1        A          68     5    30
2        B          13    34    75
3        C          60    50    50
4        D          98    62    70
5        E          78    60    82

col1    13
col2    34
col3    75
Name: (2, B), dtype: int32

2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [79]:
array=[[1,1,3,3,5],['A','B','C','D','E']]
index=pd.MultiIndex.from_arrays(array,names=['Category','Sub-cat'])
df7=pd.DataFrame(np.random.randint(1,101,size=(5,3)),index=index,columns=['col1','col2','col3'])

display(df7)

print(df7.groupby(['Category','Sub-cat']).sum())

                  col1  col2  col3
Category Sub-cat
1        A          26    43    15
         B          97    90    56
3        C          13     1     1
         D          79    17    27
5        E          43    67    15

                  col1  col2  col3
Category Sub-cat
1        A          26    43    15
         B          97    90    56
3        C          13     1     1
         D          79    17    27
5        E          43    67    15

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [87]:
date_rng=pd.date_range(start='2025-01-01',end='2025-12-31',freq='D')
df8=pd.DataFrame({'date':np.random.choice(date_rng,size=20),
                 'Category':np.random.choice(['A','B','C'],size=20),
                'Value':np.random.randint(1,1000,size=20)})

display(df8)

df8.pivot_table(values='Value',index='date',columns='Category',aggfunc='sum',fill_value=0)

         date Category  Value
0  2025-11-11        C      1
1  2025-05-28        B     44
2  2025-04-06        A    975
3  2025-02-11        B    600
4  2025-12-16        C     47
5  2025-01-07        C    826
6  2025-10-13        B    938
7  2025-02-06        B    666
8  2025-09-25        B    159
9  2025-12-22        B    214
10 2025-12-07        A    643
11 2025-01-16        C    895
12 2025-11-11        C     64
13 2025-08-22        C    775
14 2025-10-24        C    433
15 2025-06-07        A    163
16 2025-04-08        C    389
17 2025-11-11        A    700
18 2025-03-12        B    580
19 2025-09-28        C    258

Category      A    B    C
date
2025-01-07    0    0  826
2025-01-16    0    0  895
2025-02-06    0  666    0
2025-02-11    0  600    0
2025-03-12    0  580    0
2025-04-06  975    0    0
2025-04-08    0    0  389
2025-05-28    0   44    0
2025-06-07  163    0    0
2025-08-22    0    0  775
2025-09-25    0  159    0
2025-09-28    0    0  258
2025-10-13    0  938    0
2025-10-24    0    0  433
2025-11-11  700    0   65
2025-12-07  643    0    0
2025-12-16    0    0   47
2025-12-22    0  214    0

2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

In [94]:
date_rng=pd.date_range(start='1905',end='2025',freq='YE')
df82=pd.DataFrame({'Year':np.random.choice(date_rng,size=20),
                   'Quater':np.random.choice(['Q1','Q2','Q3','Q4'],size=20),
                   'Revenue':np.random.randint(1,1000,size=20)})
display(df82)

df82.pivot_table(values='Revenue',index='Year',columns='Quater',aggfunc='sum',fill_value=0)

         Year Quater  Revenue
0  1974-12-31     Q3      619
1  1985-12-31     Q2      365
2  1935-12-31     Q2      304
3  1971-12-31     Q1      215
4  2013-12-31     Q3      852
5  1999-12-31     Q2      764
6  1925-12-31     Q3      638
7  1918-12-31     Q3      274
8  2003-12-31     Q4      209
9  1931-12-31     Q3       59
10 1951-12-31     Q1      262
11 1967-12-31     Q2      392
12 1962-12-31     Q1      382
13 1956-12-31     Q3       95
14 1957-12-31     Q4      529
15 2001-12-31     Q2      962
16 1961-12-31     Q3      508
17 2002-12-31     Q3      392
18 2006-12-31     Q3      369
19 2007-12-31     Q3      242

Quater       Q1   Q2   Q3   Q4
Year
1918-12-31    0    0  274    0
1925-12-31    0    0  638    0
1931-12-31    0    0   59    0
1935-12-31    0  304    0    0
1951-12-31  262    0    0    0
1956-12-31    0    0   95    0
1957-12-31    0    0    0  529
1961-12-31    0    0  508    0
1962-12-31  382    0    0    0
1967-12-31    0  392    0    0
1971-12-31  215    0    0    0
1974-12-31    0    0  619    0
1985-12-31    0  365    0    0
1999-12-31    0  764    0    0
2001-12-31    0  962    0    0
2002-12-31    0    0  392    0
2003-12-31    0    0    0  209
2006-12-31    0    0  369    0
2007-12-31    0    0  242    0
2013-12-31    0    0  852    0

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [98]:
df9=pd.DataFrame(np.random.randint(1,1000,size=(5,3)),columns=['A','B','C'])
display(df9)

df9=df9.apply(lambda x:x*2)
display(df9)

     A    B    C
0  762  569  964
1  861  867  683
2  901  872   11
3   31  376  832
4  701  965  817

      A     B     C
0  1524  1138  1928
1  1722  1734  1366
2  1802  1744    22
3    62   752  1664
4  1402  1930  1634

2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [101]:
df92=pd.DataFrame(np.random.randint(1,1000,size=(6,3)),columns=['A','B','C'])
display(df92)

df92['Sum']=df92.apply(lambda x:x.sum(), axis=1)
display(df92)

     A    B    C
0  157  516  695
1  640  522  417
2  267  493   83
3  181  235  206
4  722  692  501
5  524  193  946

     A    B    C   Sum
0  157  516  695  1368
1  640  522  417  1579
2  267  493   83   843
3  181  235  206   622
4  722  692  501  1915
5  524  193  946  1663

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.

In [103]:
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
display(text_data.str.upper())

0         APPLE
1        BANANA
2        CHERRY
3          DATE
4    ELDERBERRY
dtype: object

2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [105]:
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
display(text_data.str[:3])

0    app
1    ban
2    che
3    dat
4    eld
dtype: object